title: "My News Blog"
description: "Latest articles and updates"
url: "https://akongoben.github.io"
theme: null
remote_theme: "mmistakes/minimal-mistakes@4.26.1"
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Ben Akongo"
  bio: "News and updates blog"
  location: "Canada"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single

